@baseUrl = http://localhost:8080/geospatial/images
@token = # PASTE_TOKEN_HERE (If authentication is needed for these endpoints)
@projectId = # Set this based on an existing project
@imageId = # Set this after adding an image
@imageName = Landsat_Image_1
@newImageName = Sentinel_Image_2

### Add a new image
# @name addImage
POST {{baseUrl}}/add
# Authorization: Bearer {{token}} # Uncomment if auth is required
Content-Type: application/json

{
  "name": "{{imageName}}",
  "projectId": "{{projectId}}",
  "source": "Landsat 8",
  "acquisitionDate": "2025-04-02T10:00:00Z",
  "resolution": 30,
  "cloudCover": 10.5,
  "metadata": {
    "sensor": "OLI/TIRS",
    "path": 15,
    "row": 30
  },
  "storageUrl": "s3://bucket/path/to/{{imageName}}.tif"
  // Add other fields based on ImageDTO
}

> {%
    // Capture the created image ID if possible (depends on response structure)
    // Example: client.global.set("imageId", response.body.data.id); 
%}


### Rename Image
# Requires valid imageId and projectId
PUT {{baseUrl}}/{{imageId}}/rename?newName={{newImageName}}&projectId={{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required


### Get All Images (Paginated)
GET {{baseUrl}}?page=0&size=10&sort=acquisitionDate,desc
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Get Image by Name and Project ID
# Requires valid projectId and imageName
GET {{baseUrl}}/name/{{projectId}}/{{imageName}}
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Get Image by ID
# Requires valid imageId
GET {{baseUrl}}/{{imageId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Get Images by Project ID
# Requires valid projectId
GET {{baseUrl}}/by-project/{{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Get Image by Image ID and Project ID
# Requires valid imageId and projectId
GET {{baseUrl}}/{{imageId}}/project/{{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Count Images in Project
# Requires valid projectId
GET {{baseUrl}}/count/{{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required
Accept: application/json


### Delete Image by ID
# Requires valid imageId
# Be careful using this!
DELETE {{baseUrl}}/{{imageId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required


### Delete Image by Image ID and Project ID
# Requires valid imageId and projectId
# Be careful using this!
DELETE {{baseUrl}}/{{imageId}}/project/{{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required


### Delete All Images by Project ID
# Requires valid projectId
# Be careful using this!
DELETE {{baseUrl}}/by-project/{{projectId}}
# Authorization: Bearer {{token}} # Uncomment if auth is required


### Bulk Delete Images
# Requires a list of image IDs in the body
# Be careful using this!
DELETE {{baseUrl}}/bulk-delete
# Authorization: Bearer {{token}} # Uncomment if auth is required
Content-Type: application/json

[
  "image_id_1", 
  "image_id_2"
  // Add actual image IDs to delete
]
