@baseUrl = http://localhost:8080/geospatial/processing

### Save processing results
# @name saveProcessingResults
POST {{baseUrl}}/save
Content-Type: application/json

{
  "imageId": "65e4494799452b2b15d33c99",
  "results": {
    "ndvi": "http://example.com/ndvi.tif",
    "evi": "http://example.com/evi.tif"
  }
}

### Get processing results by ID
# @name getProcessingResultsById
GET {{baseUrl}}//65e4494799452b2b15d33c99

### Get processing results by image ID
# @name getProcessingResultsByImageId
GET {{baseUrl}}/image/65e4494799452b2b15d33c99

### Get all processing results
# @name getAllProcessingResults
GET {{baseUrl}}?page=0&size=10

### Delete processing results by ID
# @name deleteProcessingResultsById
DELETE {{baseUrl}}//65e4494799452b2b15d33c99

### Delete processing results by image ID and results ID
# @name deleteProcessingResultsByImageId
DELETE {{baseUrl}}/image/65e4494799452b2b15d33c99/65e4494799452b2b15d33c99

### Update processing results
# @name updateProcessingResults
PUT {{baseUrl}}//65e4494799452b2b15d33c99
Content-Type: application/json

{
  "imageId": "65e4494799452b2b15d33c99",
  "results": {
    "ndvi": "http://example.com/ndvi.tif",
    "evi": "http://example.com/evi.tif",
    "ndwi": "http://example.com/ndwi.tif"
  }
}

### Bulk save processing results
# @name bulkSaveProcessingResults
POST {{baseUrl}}/bulk-save
Content-Type: application/json

[
  {
    "imageId": "65e4494799452b2b15d33c99",
    "results": {
      "ndvi": "http://example.com/ndvi1.tif",
      "evi": "http://example.com/evi1.tif"
    }
  },
  {
    "imageId": "65e4494799452b2b15d33c98",
    "results": {
      "ndvi": "http://example.com/ndvi2.tif",
      "evi": "http://example.com/evi2.tif"
    }
  }
]
