@baseUrl = http://localhost:8080/api
@email = yobtot8@gmail.com
@password = 97025244
@username = testuser
@userId = # Will be set after signup or retrieved manually
@token = # Will be captured from signin response
@resetToken = # Will be obtained from forgot-password process (e.g., email)

### Register a new user
# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "roles": ["THEMATICIAN"]
}

### Authenticate user (Sign in)
# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("userId", response.body.id); // Assuming the response includes the user ID
%}

### Get user by ID
# Requires a valid userId
GET {{baseUrl}}/thematician/account/{{userId}}
Authorization: Bearer {{token}}

Accept: application/json

### Update user account
# Requires authentication (token) and a valid userId
PUT {{baseUrl}}/account/update/{{userId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "{{username}}_updated",
  "email": "{{email}}",
  "currentPassword": "{{password}}",
  "newPassword": "newPassword456" 
}

### Initiate password reset
POST {{baseUrl}}/forgot-password
Content-Type: application/json

"{{email}}"


### Reset password with token
# Requires a valid resetToken obtained via email/other means
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "{{resetToken}}",
  "newPassword": "newPassword789"
}


### Delete user account
# Requires authentication (token) and a valid userId
# Be careful using this, it permanently deletes the user!
DELETE {{baseUrl}}/thematician/signout/{{userId}}
Authorization: Bearer {{token}}
